### ISSUE TITLE
[建議] 強震監視器時間格式

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/DPIP#117]
### ✍🏻 描述詳細情況
* 預期效果:
希望可以改成 00:00:00 的格式

* 實際效果:
1、2、3格式

### 📑 相關資訊
* 版本:
-

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明:
-

其他連結
https://discord.com/channels/926545182407688273/1255174517249278005

**Comment by lowrt** [comment]
#114
