### ISSUE TITLE
[問題回報] 無接收通知

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/DPIP#118]
### ✍🏻 描述詳細情況
* 預期效果:
收到地震相關通知

* 實際效果:
沒有收到

### 📑 相關資訊
* 版本:
iPhone 15 Pro
17.5.1

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明:

其他連結
https://discord.com/channels/926545182407688273/1254703103316594759

**Comment by 2008-04-03** [comment]
FCM上寫發布地區有包含南投縣
但確認南投市沒有接收到 作業系統仍是上面所敘述 DPIP版本為1.3.6(2
![IMG_4456](https://github.com/ExpTechTW/DPIP/assets/129482990/5307f7c7-b688-4ebf-9e56-5681f6ef3d9e)

**Comment by whes1015** [comment]
我需要他的 token

**Comment by lowrt** [comment]
@whes1015 

(這位不確定，明天再問)
fVU8Ei-PkkvxsNyd6N_JJh:APA91bGQIpxNSeT2ozl2sIDmRAqtl__0dqXraSvGXs71ByMXYE1pjc3nc_AY0c4wEg7MU1eSPuFUgQUoAOBiQWqUCIyEAob7nYGAT1qxMHv66l6jSVLbnSIGz1wB5oa-FQKtrjFd0i-9

(這是手動所在地，沒變動過)
ez4bHEK0Y0LGkxN1FzdD8Z:APA91bHOe6arM2HDA2-KshrtEc8NxFmNjSREmxFWqWGEDjSVxZxUwMqEPoM7L2JR-1NEh6K6bluRFRRxXcahDQdcbhktYv1sooZDmyEITqOuB7MbOI2PC_dmHeoPEGbM-u9VpZhfbews
