### ISSUE TITLE
[問題回報] 地震發生時DPIP強震監視器測站資料跑不出來

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/DPIP#119]
### ✍🏻 描述詳細情況
* 預期效果:
隨時都要有資料

* 實際效果:
地震發生時DPIP強震監視器測站資料跑不出來，地震震完才顯示資料

### 📑 相關資訊
* 版本:
DPIP: 1.3.0 測試版

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明:
-

其他連結

Discord
https://discord.com/channels/926545182407688273/1255452012355518584

**Comment by Yoyochou0901** [comment]
ExpTechTW/API#136

**Comment by ChrisThor09280** [comment]
DPIP的IOS在地震感測時完全沒有資料顯示，地震報告出來也沒有提示聲音。
