### ISSUE TITLE
[問題回報] 定位更新

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/DPIP#120]
### ✍🏻 描述詳細情況
* 預期效果:
打開app顯示目前位置（新竹縣竹東鎮）

* 實際效果:
顯示的是新竹縣新埔鎮

### 📑 相關資訊
* 版本:
DPIP: 1.3.0
安卓: 14
手機型號: Samsung Galaxy S23+

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明:
-

其他連結

Discord
https://discord.com/channels/926545182407688273/1255480110455197796

**Comment by 2008-04-03** [comment]
需重新啟動**_自動設定定位_**功能所在地才正常

**Comment by 2008-04-03** [comment]
需重新啟動`自動設定定位`定位才正常
