### ISSUE TITLE
DPIP搖震檢測沒反應，地震報告及感測也沒跳出沒有通知或聲音

### ISSUE THREAD

**Issue by ChrisThor09280** [ExpTechTW/DPIP#124]
### 平台

iOS

### 版本

1.3.0

### 裝置

IOS

### 內文

DPIP的IOS顯示地震感測時沒有數據，地震報告完全沒有提示聲音。

**Comment by lowrt** [comment]
您好，能詳細點嗎？
例如你的所在地 縣市震度

**Comment by ChrisThor09280** [comment]
> 您好，能詳細點嗎？

人在台北市中正區，就是有地震檢測TREM有反應時，同步觀看DPIP監測畫面，但監測畫面會定格在檢測之前，有震度檢測畫面是空的，而地震報告出爐，也無地震通知。還是說是我所在地有震度才會通知呢?

**Comment by whes1015** [comment]
> > 您好，能詳細點嗎？
> 
> 人在台北市中正區，就是有地震檢測TREM有反應時，同步觀看DPIP監測畫面，但監測畫面會定格在檢測之前，有震度檢測畫面是空的，而地震報告出爐，也無地震通知。還是說是我所在地有震度才會通知呢?

App 的通知門檻很高，基本只對影響區域發布通知。

**Comment by ChrisThor09280** [comment]
> > > 您好，能詳細點嗎？
> > 
> > 
> > 人在台北市中正區，就是有地震檢測TREM有反應時，同步觀看DPIP監測畫面，但畫面監測會定格在檢測之前，有震度檢測畫面是空的，而報告地震出爐，也無地震通知。說是我駐有震度才會通知呢？
> 
> App的通知中心，基本上只針對影響區域發布通知。

那想問一下就是監測畫面在有地震檢測時，所有測站都會看不到，時間會停在地震檢測發生前，這部分會調整嗎?
另外就是想問未來有沒有可能設計可以自己設定地震通知呢?

**Comment by whes1015** [comment]
> > > > 您好，能詳細點嗎？
> > > 
> > > 
> > > 人在台北市中正區，就是有地震檢測TREM有反應時，同步觀看DPIP監測畫面，但畫面監測會定格在檢測之前，有震度檢測畫面是空的，而報告地震出爐，也無地震通知。說是我駐有震度才會通知呢？
> > 
> > 
> > App的通知中心，基本上只針對影響區域發布通知。
> 
> 那想問一下就是監測畫面在有地震檢測時，所有測站都會看不到，時間會停在地震檢測發生前，這部分會調整嗎? 另外就是想問未來有沒有可能設計可以自己設定地震通知呢?

第一個問題可以參考 #119 ，那是伺服器的問題，已經開啟 issue 追蹤，若有新發現，可以到那個 issue 回報。
第二個問題，目前有在規劃的只有設定通知語言(你提的那些是做的出來的，只是出於使用上的考量，目前沒有打算實做)。

**Comment by lowrt** [comment]
已修復，敬請期待下個版本推出
