### ISSUE TITLE
dev: 自動定位設定介面邏輯

### ISSUE THREAD

**Issue by kamiya10** [ExpTechTW/DPIP#127]
### Checklist

- [x] 自動定位開關邏輯
  - 開啟
    - [x] 檢查並請求定位權限
    - [x] 檢查並請求總是背景定位權限
    - [x] 啟動背景定位服務
    - [x] 設定 `auto-location` => true
  - 關閉
    - [x] 停止現有自動定位服務 
    - [x] 設定 `auto-location` => false

### 相關檔案

https://github.com/ExpTechTW/DPIP/blob/c0e633895879850f9b73d7fd377de88fa4a4bdac/lib/route/settings/content/location.dart#L16-L28

**Comment by yayacat** [comment]
[fix: location](https://github.com/ExpTechTW/DPIP/commit/26c7b4b50db798b812e206fe958db40d0bf54e64)

**Comment by yayacat** [comment]
[e5e90f1](https://github.com/ExpTechTW/DPIP/commit/e5e90f1004c53fe01abf0d3e71cc5018bb9e43af)

**Comment by yayacat** [comment]
#130

**Comment by kamiya10** [comment]
@yayacat 看能不能有這個流程
對用戶端來說會比較友善一點
<img width="2032" alt="flow" src="https://github.com/ExpTechTW/DPIP/assets/58339640/0aaf4662-3b7d-4ae0-b336-81e4305ff708">
