### ISSUE TITLE
自動定位失效

### ISSUE THREAD

**Issue by thelittlerocket** [ExpTechTW/DPIP#259]
### 平台

iOS

### 版本

18.1

### 裝置

iPhone 15 Pro Max

### 內文

使用自動定位無作用，手動設定地區正常。

### 影片/照片

![IMG_7607](https://github.com/user-attachments/assets/dd99c3a5-d8bd-4015-8b47-b103f48d0ab4)
![IMG_7606](https://github.com/user-attachments/assets/1dec06e0-fc44-4e40-8a92-3e4238e49673)

**Comment by lowrt** [comment]
已確認問題，感謝回報！
