### ISSUE TITLE
[問題回報] 監測器字體顏色

### ISSUE THREAD

**Issue by huangmayor0905** [ExpTechTW/DPIP#30]
### ✍🏻 描述詳細情況
* 預期效果: 監測器頁面為淺色主題（時間及震度）字體應為黑色
* 實際效果: 字體仍為白色，看不到時間及震度

![image](https://github.com/ExpTechTW/DPIP/assets/92105176/fe72a222-f7fe-412b-9321-a42aedc88a58)

### 📑 相關資訊
* 版本: 1.1.2

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: 手機型號 Pixel 7

**Comment by lowrt** [comment]
您好，淺色介面強震監視器字體已修復，感謝您回報~
