### ISSUE TITLE
[問題回報] DPIP 參數顯示異常

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/DPIP#59]
### ✍🏻 描述詳細情況
* 預期效果: 顯示完整參數
* 實際效果: 部分參數被截掉

### 📑 相關資訊
* 版本: 1.2.1

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: 暫無

####  此檔案由 ExpTech.tw 設計製作
![3](https://github.com/ExpTechTW/DPIP/assets/50204240/aafbe445-975b-478b-a88e-7eb3daa4ede4)

![4](https://github.com/ExpTechTW/DPIP/assets/50204240/8e78486f-1da2-4ce7-8464-0a5eba271d20)

**Comment by lowrt** [comment]
#51 已修復
EEW部分尚未移位置
