### ISSUE TITLE
[問題回報] DPIP 秒數問題

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/DPIP#60]
### ✍🏻 描述詳細情況
* 預期效果: S波抵達所在地後要顯示「抵達」
* 實際效果: S波抵達所在地後還是顯示倒數

### 📑 相關資訊
* 版本: 未知

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: 暫無

####  此檔案由 ExpTech.tw 設計製作

![5](https://github.com/ExpTechTW/DPIP/assets/50204240/0fa76c29-4fb1-4dd6-988c-523bd14d0377)

**Comment by lowrt** [comment]
圖片P/S波跑太快，會找解決方案問題
(以所在地倒數為準
