### ISSUE TITLE
[問題回報] DPIP 部分通知地區字詞消失

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/DPIP#62]
### ✍🏻 描述詳細情況
* 預期效果: 地名完整顯示
* 實際效果: 地名少字

### 📑 相關資訊
* 版本: 歷史

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: 

桃園 平鎮
台南 左鎮
高雄 前鎮
臺南 新市

**Comment by lowrt** [comment]
@whes1015 : 吃字的問題已修正了
