### ISSUE TITLE
[問題回報] DPIP 刷新地震報告 獲取異常

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/DPIP#63]
### ✍🏻 描述詳細情況
* 預期效果: 刷新重新獲取現有完整CWA地震報告
* 實際效果: 有時候會或取道一半

### 📑 相關資訊
* 版本: 1.2.3

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: https://discord.com/channels/926545182407688273/1231950467886743652

**Comment by lowrt** [comment]
已於5/24完成
