### ISSUE TITLE
[問題回報] ios 有辦法像 android 列出深度

### ISSUE THREAD

**Issue by themysciraa** [ExpTechTW/DPIP#69]
### 📑 相關資訊
* 版本:
![IMG_3574](https://github.com/ExpTechTW/DPIP/assets/49617424/725d6660-097c-43df-9760-9f617de5ecfb)
![IMG_3575](https://github.com/ExpTechTW/DPIP/assets/49617424/c0c07ce7-5ad4-4bd0-a846-cffd0dc9d4cb)

**Comment by lowrt** [comment]
IOS版 內部版已實裝深度(km)
![IMG_7891](https://github.com/ExpTechTW/DPIP/assets/37591855/1cffe03b-e9c6-4a92-80d2-4a7400cb890a)
